In [1]:
import numpy as np
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [2]:
a.dtype

dtype('float64')

In [4]:
c=np.empty(10)


In [5]:
c

array([6.95168203e-310, 6.95168203e-310, 0.00000000e+000, 0.00000000e+000,
       4.94065646e-324, 4.68325960e-310, 4.94065646e-324, 4.68325960e-310,
       6.95165821e-310, 6.95168129e-310])

In [9]:
c.shape =(5,2)
c

array([[6.95168203e-310, 6.95168203e-310],
       [0.00000000e+000, 0.00000000e+000],
       [4.94065646e-324, 4.68325960e-310],
       [4.94065646e-324, 4.68325960e-310],
       [6.95165821e-310, 6.95168129e-310]])

In [12]:
d= np.linspace(3,20,5)
d

array([ 3.  ,  7.25, 11.5 , 15.75, 20.  ])

In [14]:
e=np.arange(3,20,5)
e

array([ 3,  8, 13, 18])

In [15]:
f = np.array((10,20,30))
f

array([10, 20, 30])

In [17]:
list= [1,2,3,4,5,6,7],[1,2,3,4,5,6,7]
g=np.array((list))
g

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

In [18]:
g.shape
g

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

In [19]:
?g.shape

In [20]:
h = np.random.randint(100,size=10)
h

array([14, 82, 13,  6,  1, 36,  5, 39, 25, 25])

In [24]:
h[1]


82

In [25]:
h[0:5]

array([14, 82, 13,  6,  1])

In [26]:
h[-1]

25

In [27]:
h>40

array([False,  True, False, False, False, False, False, False, False,
       False])

In [28]:
h*2

array([ 28, 164,  26,  12,   2,  72,  10,  78,  50,  50])

In [29]:
h/2

array([ 7. , 41. ,  6.5,  3. ,  0.5, 18. ,  2.5, 19.5, 12.5, 12.5])

In [30]:
h+100

array([114, 182, 113, 106, 101, 136, 105, 139, 125, 125])

In [31]:
h-100

array([-86, -18, -87, -94, -99, -64, -95, -61, -75, -75])

In [32]:
result = np.array([20,30,40,50,60,80,90,65])
np.where(result>40,"pass","fail")

array(['fail', 'fail', 'fail', 'pass', 'pass', 'pass', 'pass', 'pass'],
      dtype='<U4')

In [ ]:
List = range(200000)
%time for n in range(1,10): r[num*5 for num in list]